# Data Validation - Telco Customer Churn

This notebook checks the dataset before EDA and modeling.

- **Dataset:** IBM Telco Customer Churn
- **Target column:** Churn

## Load Data

In [15]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/raw/Telco_Customer_Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.8500,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.9500,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.8500,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.3000,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.7000,151.65,Yes

## 1. Dataset Shape Validation

In [16]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

if df.shape[0] > 0 and df.shape[1] > 0:
    print("Dataset is not empty")
else:
    print("Dataset is empty")

Rows: 7043
Columns: 21
Dataset is not empty

**Note:** We have data to analyze. Empty file would be a problem.

## 2. Schema Validation

In [17]:
print(df.columns.tolist())
print("\nNumber of columns:", len(df.columns))
print("Duplicate columns:", df.columns.duplicated().sum())
print("Churn column exists:", "Churn" in df.columns)

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Number of columns: 21
Duplicate columns: 0
Churn column exists: True

**Note:** Churn column must be there because it is our target.

## 3. Data Type Validation

In [18]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [20]:
# TotalCharges is object - convert for checks
print("TotalCharges type:", df["TotalCharges"].dtype)
df["TotalCharges_num"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

TotalCharges type: object

**Note:** TotalCharges should be converted to number in data cleaning step.

## 4. Missing Value Validation

In [21]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges         0
Churn                0
TotalCharges_num    11
dtype: int64

In [22]:
(df.isnull().sum() / len(df) * 100).round(2)

customerID         0.0000
gender             0.0000
SeniorCitizen      0.0000
Partner            0.0000
Dependents         0.0000
tenure             0.0000
PhoneService       0.0000
MultipleLines      0.0000
InternetService    0.0000
OnlineSecurity     0.0000
OnlineBackup       0.0000
DeviceProtection   0.0000
TechSupport        0.0000
StreamingTV        0.0000
StreamingMovies    0.0000
Contract           0.0000
PaperlessBilling   0.0000
PaymentMethod      0.0000
MonthlyCharges     0.0000
TotalCharges       0.0000
Churn              0.0000
TotalCharges_num   0.1600
dtype: float64

In [23]:
blank_total = (df["TotalCharges"].astype(str).str.strip() == "").sum()
print("Blank TotalCharges:", blank_total)
print("Missing after numeric conversion:", df["TotalCharges_num"].isnull().sum())

Blank TotalCharges: 11
Missing after numeric conversion: 11

**Note:** Some new customers have blank TotalCharges when tenure is 0.

## 5. Duplicate Record Validation

In [24]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customerID:", df["customerID"].duplicated().sum())

Duplicate rows: 0
Duplicate customerID: 0

**Note:** No duplicates is good - each row is one customer.

## 6. Unique Value Analysis

In [25]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
TotalCharges_num    6530
dtype: int64

In [26]:
print("Unique customerID:", df["customerID"].nunique())
print("Total rows:", len(df))

Unique customerID: 7043
Total rows: 7043

**Note:** customerID is unique for each row. Other columns like gender have only 2 values.

## 7. Numerical Data Validation

In [27]:
df[["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges_num"]].describe()

       SeniorCitizen     tenure  MonthlyCharges  TotalCharges_num
count     7,043.0000 7,043.0000      7,043.0000        7,032.0000
mean          0.1621    32.3711         64.7617        2,283.3004
std           0.3686    24.5595         30.0900        2,266.7714
min           0.0000     0.0000         18.2500           18.8000
25%           0.0000     9.0000         35.5000          401.4500
50%           0.0000    29.0000         70.3500        1,397.4750
75%           0.0000    55.0000         89.8500        3,794.7375
max           1.0000    72.0000        118.7500        8,684.8000

In [28]:
print("Negative tenure:", (df["tenure"] < 0).sum())
print("Negative MonthlyCharges:", (df["MonthlyCharges"] < 0).sum())
print("Negative TotalCharges:", (df["TotalCharges_num"] < 0).sum())

Negative tenure: 0
Negative MonthlyCharges: 0
Negative TotalCharges: 0

**Note:** Values look reasonable. Tenure is between 0 and 72 months.

## 8. Categorical Data Validation

In [29]:
cols = ["gender", "Partner", "InternetService", "Contract", "PaymentMethod", "Churn"]

for col in cols:
    print(col, ":", df[col].unique())

gender : ['Female' 'Male']
Partner : ['Yes' 'No']
InternetService : ['DSL' 'Fiber optic' 'No']
Contract : ['Month-to-month' 'One year' 'Two year']
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn : ['No' 'Yes']

**Note:** Categories look normal - Yes/No, contract types, payment methods etc.

## 9. Target Variable Validation

In [30]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [31]:
churn_rate = (df["Churn"] == "Yes").mean() * 100
print("Churn %:", round(churn_rate, 2))

Churn %: 26.54

**Note:** About 27% churn. More customers stay than leave (imbalanced data).

## 10. Data Leakage Check

In [32]:
print("Do not use customerID in model - it is just an ID")
print("Do not use Churn as feature - it is the target")
print("TotalCharges can be used but it depends on tenure")
print("Other columns are fine to use as features")

Do not use customerID in model - it is just an ID
Do not use Churn as feature - it is the target
TotalCharges can be used but it depends on tenure
Other columns are fine to use as features

**Note:** Using target as feature would cheat the model. ID has no meaning for prediction.

## 11. Business Rule Validation

In [33]:
print("Tenure = 0 customers:", (df["tenure"] == 0).sum())

tenure_zero = df[df["tenure"] == 0]
blank = (tenure_zero["TotalCharges"].astype(str).str.strip() == "").sum()
print("Blank TotalCharges when tenure is 0:", blank)

Tenure = 0 customers: 11
Blank TotalCharges when tenure is 0: 11

In [34]:
mask = (df["tenure"] >= 1) & df["TotalCharges_num"].notna()
issue = df[mask & (df["TotalCharges_num"] < df["MonthlyCharges"])]
print("TotalCharges less than MonthlyCharges:", len(issue))

TotalCharges less than MonthlyCharges: 0

**Note:** New customers (tenure 0) may not have total charges yet. That is normal.

## 12. Validation Summary

In [35]:
print("SUMMARY")
print("--------")
print("Rows:", df.shape[0], "| Columns:", df.shape[1])
print("Target column OK: Churn present")
print("Duplicates: none")
print("Issue: TotalCharges needs numeric conversion")
print("Issue: 11 missing TotalCharges (tenure 0)")
print("Churn rate: ~27%")
print()
print("Before EDA:")
print("1. Fix TotalCharges datatype")
print("2. Handle missing TotalCharges")
print("3. Remove customerID from features")
print("4. Start EDA notebook")

SUMMARY
--------
Rows: 7043 | Columns: 22
Target column OK: Churn present
Duplicates: none
Issue: TotalCharges needs numeric conversion
Issue: 11 missing TotalCharges (tenure 0)
Churn rate: ~27%

Before EDA:
1. Fix TotalCharges datatype
2. Handle missing TotalCharges
3. Remove customerID from features
4. Start EDA notebook